### ISSUE TITLE
Add `touch`

### ISSUE THREAD

**Issue by BigBlueHat** [glynnbird/couchshell#1]
First and foremost, this is amazing @glynnbird ! :smile:

Second, on reading through the list of commands, I found myself looking for `touch` support. :smiley: Doubt it'd be a big add, but think it'd be useful especially when just starting out to craft a Document ID space to see how it looks.

Other ideas are forming in my only partly caffeinated brain, but I'll stop here for now. :grin:

**Comment by glynnbird** [comment]
Glad you like it @BigBlueHat . I've added 'touch'. It either
- creates new empty documents
- loads and saves existing documents

:)

**Comment by BigBlueHat** [comment]
:heart:
